### ISSUE TITLE
UI is buggy

### ISSUE THREAD

**Issue by RudiAusBuddeln** [taw/hoi4#10]
As can be seen [here](https://i.imgur.com/prBrNLY.png), the battalion select overlaps with the statistics, at least in my browser.

**Comment by taw** [comment]
Which browser is that?

I only test on Chrome, but it should be easy to fix if I know what you're using.

**Comment by taw** [comment]
@RudiAusBuddeln I shrunk that number field, it had no reason to be that big, so it should make it a bit better.
I still have no idea why it's been overflowing, and I can't verify this since I have no idea what kind of browser you got this bug on.

**Comment by RudiAusBuddeln** [comment]
I use Firefox. It works well in Chrome though, so I have inspected the site and found that the `<html>` has the CSS property `-webkit-text-size-adjust: 100%;` as defined in `_reboot.scss` that must be included by react somewhere? Anyway, Firefox has no support for this property. The author said `Normalization of HTML elements, manually forked from Normalize.css to remove
 styles targeting irrelevant browsers while applying new styles.` so Firefox is an irrelevant browser now. Okay.

**Comment by taw** [comment]
CSS reset just makes all browsers act as similar as possible, and has nothing to do with this issue.

It looks like Firefox had a different idea about `flex-basis` for inputs. It should work now.

But yeah, Firefox is not very popular (~5% according to Wikipedia), so people don't really test it, and occasional issues can happen. You should just report them, usually it's just a few lines of CSS to fix it.

**Comment by taw** [comment]
@RudiAusBuddeln Is this fixed for you?

**Comment by taw** [comment]
Closing as I assume it's fixed now.
