### ISSUE TITLE
Custom styles or sets

### ISSUE THREAD

**Issue by Sepera-okeq** [taw/hoi4#13]
Will support for custom settings be implemented? As the author of EC, I would like to use this product to improve development, but I don't really understand how to modify or create my own style. 
I have completely different types of units, so I can't use your tool, but I would like support for custom styles or sets.
Thank!

**Comment by taw** [comment]
What do you mean by custom sets / styles?

[I have a script that parses game data for any mods and exports into json](https://github.com/taw/paradox-tools/tree/master/hoi4_division_designer), but it's not fully automated, and needs some manual edits for each mod, especially for mod that do anything unusual.

The only ones I ran it on are Kaiserreich, Road to 56 (both very close to vanilla), and old version of Millenium Dawn (before they started doing weird stuff, and I ended up dropping them).

Also what's EC? [I guess this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2000532465)?

**Comment by Sepera-okeq** [comment]
Yes, I'm the author. 
So you need to run the script first, and then implement it in hoi4/src/database/ ?

> What do you mean by custom sets / styles?

Yes, you said about the data, I just want to enter my data to make it easier to work.

> I have a script that parses game data for any mods and exports into json, but it's not fully automated, and needs some manual edits for each mod, especially for mod that do anything unusual.

Figured it out, like I understood. I'll try it at my place.

**Comment by taw** [comment]
Yes, you need to run the script pointing at game files and mod files (as a folder not as a zip).
Then it will generate json for you.

```
ruby  bin/import_data your_mod_name /path/to/game /path/to/you/mod
```

Getting importer to work with your mod might take some work.

It will generate `data/your_mod_name.json`, which you can drop to division designer to `src/database/your_mod_name.json`.

Division designer needs only tiny 2 changes:

* on top of `src/database/Database.js` it has list of mods
* in `src/components/ModSelector.js` it has list of buttons for switching mods

**Comment by taw** [comment]
Do you need any support for this, or can this issue be closed?

**Comment by Sepera-okeq** [comment]
No. Thanks.
