### ISSUE TITLE
Hidden text

### ISSUE THREAD

**Issue by joao-esteves** [taw/hoi4#14]
## Issue

There's a lot of free space on regular desktop screens, and yet the doctrine selector cuts off some text and some recon companies take up two lines.

Example: https://user-images.githubusercontent.com/17863203/104970018-07023c00-59e2-11eb-9b5c-4a6236ed13a9.png

## Proposal

Widen the left column on bigger screens to accommodate for more text. Values:
- 1200px, the width of the ``xl`` Bootstrap breakpoint, for the window's minimum size
- 1.33fr for the first column's grid width (400px/300px ≈ 1.33)
- 400px for the max-width of the first column's elements

I would make a pull request myself, but I don't have authorization. Could you open the repository for open-source development, or make me a contributor?

Below, there's a draft on a window exactly 1200px wide. It might also be a good idea to make the date and name inputs inline, and change something on the battalion selectors so they're not so large.

![image](https://user-images.githubusercontent.com/17863203/104969326-0bc5f080-59e0-11eb-83bf-65677e22a664.png)

**Comment by taw** [comment]
Yeah that makes sense. They didn't have those long support names back when I created it.

You can use Fork button to create your local fork, and PR this way. That's the usual way to do PRs on github.

Either way, I'll take a look at it.

**Comment by taw** [comment]
Is the new CSS working for you now for all screen widths?

**Comment by joao-esteves** [comment]
> Is the new CSS working for you now for all screen widths?

It's a lot more pleasant now, yes, thanks!

Didn't realize that was the standard way on Github, sounds weird from a practical viewpoint. I might get to it this week if I come up with more improvements.

**Comment by taw** [comment]
@Joao611 Do you need any other fixes, or is this all done?

**Comment by joao-esteves** [comment]
> @Joao611 Do you need any other fixes, or is this all done?

I'd like to make this easier and faster to use while somehow making the layout more similar to the game's division designer, but I can't come up with anything besides high-level semi-ideas. You can close this now.

**Comment by taw** [comment]
Game's division designer looks nice, but it hides a lot of stuff we have here, so I don't think that's a design to go.

Also people keep asking for extra features like ability to pick specific techs etc. - my engine can handle that, but I have no idea how to UX that.
