### ISSUE TITLE
Feature suggestion: battlefield sitution controls that modify combat stats

### ISSUE THREAD

**Issue by erwinhalik** [taw/hoi4#16]
Hey Tomasz, love your hoi4 tool. I use it all the time.

I have a suggestion for a feature that would make planning divisons according to the battleground easier:
A set of controls that sit over the combat stats where you can choose the battle situation. Controls would probably be action(attacking or defending), terrain features(small/large river crossing, amphibious landing, fort level) and terrain type (Desert, Forrest, Hills ...).

When a sitatuion is set, the combat stats would then change according to the current terrain modifiers already present in the app.

**Comment by taw** [comment]
What would be UI for that? I don't think it would really fit the UI.

**Comment by erwinhalik** [comment]
Yeah it would be hard to make this UX friendly without overloading. I'm thinking on checkboxes and dropdowns. I might sketch something up, so you can decide for yourself if you could fit it in.

**Comment by taw** [comment]
Closing this issue for now, as it's unclear how UX for this would work.

In principle this could happen someday, but it's not actionable without some good UX.
