### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by RudiAusBuddeln** [taw/hoi4#17]
Having a way to directly compare two divisons would be fantastic. Preferably showing the differences in percentages in colors et cetera.

**Comment by taw** [comment]
For viewing multiple divisions you can just open multiple browser windows or tabs, so putting them all on one page doesn't really add much value.

Now for a full comparison view, that would be nice, but the UI is already very crowded, so I'd prefer to see some ideas how it could all be arranged.

**Comment by joao-esteves** [comment]
How about a system similar to the game's? In the game, when you edit a template, it shows the different stats with green/red colors relatively to the original, saved template. For this designer, we could add a 'Compare' button to the bottom of the UI, which would display, for each stat, the current value in parenthesis, while the regular numbers would change depending on the next changes to the template. So for example, a stat would become "Defense 230.1 (187.7)" and the number(s) would be green to highlight the stat's upgrade.

I don't know how the colors would work out with the terrain modifiers, though; maybe keep those colors as-is.

The button placement could be this:

![image](https://user-images.githubusercontent.com/17863203/110373689-aee1d080-8047-11eb-881d-1ddb83ad7e02.png)

I moved the save elements to the next line to clean it up, but it is odd how the 'Save' button isn't together with the rest. There are too many buttons, but I don't have a suggestion for that.

**Comment by taw** [comment]
Not so much the button, it's about all those comparisons. So that "+2.2%" would become "+2.2% ⬆️ +0.9%" etc.
And so for every other number in the second and third column.

That would get extremely crowded.

**Comment by RudiAusBuddeln** [comment]
> For viewing multiple divisions you can just open multiple browser windows or tabs, so putting them all on one page doesn't really add much value.

Yes, but – kind of ironically – the UI is so crowded that you must either compare them by viewing each attribute next to each other in a window or aggressively switch tabs and see the values change. Either way is quite a strain and the user must always manually compare the values instead of a nicely colored percentage.

I think the suggestion by @Joao611 is good – adding a button to compare it with an existing, "base" divison. Here is a little edit:

![Screenshot from 2021-03-20 16-28-30](https://user-images.githubusercontent.com/66952759/111875318-6e644a00-8999-11eb-8fb5-81926b2b7e0c.png)

While creating this, I also wondered whether any increase should be green or whether some properties improve by going down. For example supply usage going up in green would be quite weird.

In order to get rid of a couple buttons, maybe the mod buttons could become a `<select>` at the very bottom? They are likely much less used than the other ones.

**Comment by joao-esteves** [comment]
> ![Screenshot from 2021-03-20 16-28-30](https://user-images.githubusercontent.com/66952759/111875318-6e644a00-8999-11eb-8fb5-81926b2b7e0c.png)

I'd rather have absolute numbers, like ingame, since percentages don't tell me much. But otherwise yeah, it doesn't get too crowded imo.

**Comment by taw** [comment]
I'm still sort of considering doing something like that.

**Comment by taw** [comment]
I might change my mind someday, but as I currently have no real plans to rewrite the app for No Step Back, I'll close the issue.
