### ISSUE TITLE
Update to 1.11 - No Step Back

### ISSUE THREAD

**Issue by Steinardarri** [taw/hoi4#27]

**Comment by taw** [comment]
Would be nice, but I don't currently plan to do this.

If I understand it correctly, the app would need a whole new system for designing tanks etc., and that's potentially nearly as much work as the original app was.

**Comment by TK3600** [comment]
Could we have a compromise? We skip the tank element entirely and just port rest of the stat change as a beta feature? Call it 1.11.4 beta.

**Comment by taw** [comment]
I'm not sure how doable that would be, I haven't checked the files if we can just disable that part.

Do people without DLC just have old style tanks?

**Comment by TK3600** [comment]
> I'm not sure how doable that would be, I haven't checked the files if we can just disable that part.
> 
> Do people without DLC just have old style tanks?

that is correct, and tbh the DLC tank designer is too unbalanced it is better with old tanks anyway.

**Comment by TK3600** [comment]
Any progress on this?

**Comment by taw** [comment]
It's very low on my TODO list. I might do this someday, but no real plans.

**Comment by taw** [comment]
I might change my mind someday, but as I currently have no real plans to rewrite the app for No Step Back, I'll close the issue.

If anyone would like to take it over, I can offer assistance.
