### ISSUE TITLE
Shareable Links

### ISSUE THREAD

**Issue by brian-lim-42** [taw/hoi4#4]
Hi

Would be nice to get shareable links

That way we can share templates with people

Thanks!

**Comment by taw** [comment]
Hi,

So the technical problem is mostly that there's no database on this app (it's using your browser's `localStorage`), and template data is pretty long so it would mean very long links. But it could be done.

**Comment by brian-lim-42** [comment]
Only inputs are numbers and drop-down choices yes? Should be possible to encode that in say base64 in relatively short string I would be willing to help later, thanks

**Comment by taw** [comment]
Yeah, it will probably be some kind of JSON.stringify to Base64, then put into `#`.

**Comment by taw** [comment]
[It's working now](https://taw.github.io/hoi4/#eyJtb2ROYW1lIjoidmFuaWxsYSIsInllYXIiOjE5MzYsImRvY3RyaW5lIjpudWxsLCJ1bml0cyI6W1sxMCwiaW5mYW50cnkiXSxbMTAsImFydGlsbGVyeV9icmlnYWRlIl0sWzAsImluZmFudHJ5Il1dLCJzdXBwb3J0Ijp7ImFydGlsbGVyeSI6dHJ1ZX0sInVwZ3JhZGVzIjp7fSwiZGl2aXNpb25OYW1lIjoiQW1hemluZyBEaXZpc2lvbiJ9). At least in Chrome.

No idea if it works in any other browser.

**Comment by brian-lim-42** [comment]
@taw thanks!
