### ISSUE TITLE
Consider adding a total combat data

### ISSUE THREAD

**Issue by ghost** [taw/hoi4#46]
Take a division of 7inf and 2art an example.
Each division has a soft attack of 97, combat width of 20, and ic cost of 602.
Therefore, in a 96-width battle, 4 divisions can be involved, with a **soft attack per battle** of 97*4=388.
Also, considering the ic cost, the **soft attack per ic** ratio should be 97/602=0.161.
These values can be very helpful when designing divisions, otherwise there won't be any difference between your calculator and the in-game designer.

**Comment by taw** [comment]
Well, the project is no longer under development, as there are so many equipment designers now that it would need a full rewrite, so I'm not taking any requests.

But if you're interested in taking the code and continuing it, it's all Open Source.

**Comment by ghost** [comment]
sad to hear about that :( i'll try to continue it

**Comment by taw** [comment]
I'll close this issue, as the code isn't really maintained. If anyone ever wants to resurrect it, it might make sense to reopen it.
