### ISSUE TITLE
Armored car battalions always use interwar equipment

### ISSUE THREAD

**Issue by RemansParadox** [taw/hoi4#8]
Armored cars have two upgrades in the tech tree, but the division designer always uses the interwar equipment.

**Comment by taw** [comment]
Thanks, I'll take a look why it doesn't see the upgrades.

**Comment by taw** [comment]
Well, it's even worse, as there are two 1942 models - Improved Armored Car, and Anti-Tank Armored Car, and they go into templates based on whichever you decide to produce. That doesn't fit the UI right now. (but it should still do either I / II / III, or I / II / AT).

**Comment by taw** [comment]
Oh wow, I assumed all equipment matches `name_level` pattern, and cars use  `gw_armored_car_equipment`, `armored_car_equipment_1`, `armored_car_equipment_2`, `armored_car_at_equipment`, which doesn't follow this pattern at all.

**Comment by taw** [comment]
OK, it now works, using AT car over III, quite arbitrarily.

**Comment by taw** [comment]
Closing as this is fixed as far as I know (except the issue of having 2 armored car types in same year, and one being chosen arbitrarily)
